name:                tie
version:             0.1.0.0
github:              "notquiteamonad/tie"
author:              "notquiteamonad"
maintainer:          "44178347+notquiteamonad@users.noreply.github.com"
copyright:           "Copyright notquiteamonad 2021"

default-extensions:
  - OverloadedStrings

description:         Please see the README on GitHub at <https://github.com/notquiteamonad/tie#readme>

dependencies:
- base >= 4.7 && < 5

extra-source-files:
- README.md

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  tie-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tie
