name: tie
version: 0.1.0.0
github: "notquiteamonad/tie"
author: "notquiteamonad"
maintainer: "44178347+notquiteamonad@users.noreply.github.com"
copyright: "Copyright notquiteamonad 2021"

default-extensions:
  - OverloadedStrings

description: Please see the README on GitHub at <https://github.com/notquiteamonad/tie#readme>

dependencies:
  - base-noprelude >= 4.7 && < 5
  - directory >= 1.3.6 && < 1.4
  - fsnotify >= 0.3.0 && < 0.4
  - relude >= 0.7.0 && < 0.8
  - text >= 1.2.4 && < 1.3

extra-source-files:
  - README.md

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  tie-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tie

tests:
  tie-test:
    main: Spec.hs
    source-dirs: test
    default-extensions:
      - BlockArguments
    dependencies:
      - tie
      - hspec >= 2.7.6 && < 2.8
