name: tie
version: 0.1.1.1
license: BSD3
github: "notquiteamonad/tie"
author: "notquiteamonad"
maintainer: "44178347+notquiteamonad@users.noreply.github.com"
copyright: "Copyright notquiteamonad 2021"

default-extensions:
  - OverloadedStrings

description: Please see the README on GitHub at <https://github.com/notquiteamonad/tie#readme>

dependencies:
  - base-noprelude >= 4.7 && < 5
  - directory >= 1.3.6 && < 1.4
  - filepath >= 1.4.2 && < 1.5
  - relude >= 0.7.0 && < 0.8
  - text >= 1.2.4 && < 1.3
  - tomland >= 1.3.2 && < 1.4

extra-source-files:
  - README.md
  - ChangeLog.md
  - LICENSE

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  tie-linux:
    main: Main.hs
    source-dirs: app/linux
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - safe-coloured-text >= 0.0.0 && < 0.1
      - fsnotify >= 0.3.0 && < 0.4
      - tie
  tie-windows:
    main: Main.hs
    source-dirs: app/windows
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - fsnotify >= 0.3.0 && < 0.4
      - tie

tests:
  tie-test:
    main: Spec.hs
    source-dirs: test
    default-extensions:
      - BlockArguments
    dependencies:
      - hspec >= 2.7.8 && < 2.8
      - template-haskell >= 2.16.0 && < 2.17
      - tie
    build-tools:
      - hspec-discover >= 2.7.8 && < 2.8
