name: tie
version: 0.1.0.0
github: "notquiteamonad/tie"
author: "notquiteamonad"
maintainer: "44178347+notquiteamonad@users.noreply.github.com"
copyright: "Copyright notquiteamonad"
description: Please see the README on GitHub at <https://github.com/notquiteamonad/tie#readme>

default-extensions:
  - BlockArguments
  - DataKinds
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - GADTs
  - KindSignatures
  - LambdaCase
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StrictData
  - TypeApplications
  - TypeFamilies
  - TypeOperators

flags:
  prod:
    default: false
    description: Enable production defaults
    manual: true

ghc-options:
  - "-Wall"
  - "-Wcpp-undef"
  - "-Widentities"
  - "-Wincomplete-patterns"
  - "-Wincomplete-record-updates"
  - "-Wincomplete-uni-patterns"
  - "-Wmissing-deriving-strategies"
  - "-Wmissing-import-lists"
  - "-Wmissing-signatures"
  - "-Wpartial-fields"
  - "-Wredundant-constraints"
  - "-fplugin=Effectful.Plugin"
when:
  - condition: flag(prod)
    ghc-options:
      - "-O2"
      - "-Werror"

dependencies:
  - name: base
    version: "== 4.16.3.0"
    mixin:
      - hiding (Prelude)
  - effectful-core == 2.2.2.1
  - effectful-plugin == 1.0.0.0
  - relude == 1.1.0.0

library:
  source-dirs: src
  dependencies:
    - effectful-th == 1.0.0.1
executables:
  tie-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - "-O2"
      - "-threaded"
      - "-rtsopts"
      - "-with-rtsopts=-N"
    dependencies:
      - tie
