on:
  pull_request:
  push:
    branches:
      - main
name: build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.4'
          enable-stack: true
          stack-version: 'latest'
      - uses: actions/cache@v2.1.3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: stack
      - name: Install hlint
        run: >-
          curl -L https://github.com/ndmitchell/hlint/releases/download/v3.2.7/hlint-3.2.7-x86_64-linux.tar.gz > hlint.tgz &&
          tar xvf hlint.tgz
      - name: Lint project
        run: ./hlint-3.2.7/hlint app src test
      - name: Install stylish-haskell
        run: >-
          curl -L https://github.com/jaspervdj/stylish-haskell/releases/download/v0.12.2.0/stylish-haskell-v0.12.2.0-linux-x86_64.tar.gz > stylish-haskell.tgz &&
          tar xvf stylish-haskell.tgz
      - name: Check formatting
        run: git ls-files | grep '\.l\?hs$' | xargs ./stylish-haskell-v0.12.2.0-linux-x86_64/stylish-haskell -i && git diff-index --exit-code HEAD --
      - name: Turn off nix builds
        run: sed -i '/^nix:/,$d' stack.yaml
      - run: stack clean
      - run: stack build --fast --ghc-options -Werror
      - run: stack test --fast --ghc-options -Werror
      